import os

SECRET_KEY = os.environ.get("SECRET_KEY")
MONGODB_HOST = os.environ.get("MONGODB_HOST")
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET")

# print(f"SECRET_KEY: {SECRET_KEY}")
# print(f"MONGODB_HOST: {MONGODB_HOST}")
# print(f"GOOGLE_CLIENT_ID: {GOOGLE_CLIENT_ID}")
# print(f"GOOGLE_CLIENT_SECRET: {GOOGLE_CLIENT_SECRET}")
